### ISSUE TITLE
Error starting midlet: java.lang.NoClassDefFoundError: javax/microedition/media/PlayerListener

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Perundurai-Products/microemu#26]
```
What steps will reproduce the problem?
1.Download a prebuild midlet from http://gpsmid.sourceforge.net/prebuild/
2.Start MicroEmulator 3.0. downloaded from
http://snapshot.microemu.org/microemulator/download/microemulator-3.0.0-SNAPSHOT
.zip
(version from 08-Jan-2010)
3.Load and try to start the midlet

What is the expected output? What do you see instead?
Midlet does not startup, instead an exception occurs:
Error starting midlet
java.lang.NoClassDefFoundError: javax/microedition/media/PlayerListener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at
org.microemu.app.classloader.MIDletClassLoader.findClass(MIDletClassLoader.java:
427)
    at
org.microemu.app.classloader.MIDletClassLoader.loadClass(MIDletClassLoader.java:
201)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClassInternal(Unknown Source)
    at de.ueller.midlet.gps.GpsMid.<init>(GpsMid.java:121)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at org.microemu.app.Common.loadMidlet(Common.java:418)
    at org.microemu.app.Common.initMIDlet(Common.java:1044)
    at org.microemu.app.launcher.Launcher.commandAction(Launcher.java:121)
    at javax.microedition.lcdui.Display$DisplayAccessor$1.run(Display.java:209)
    at
org.microemu.device.ui.EventDispatcher$RunnableEvent.run(EventDispatcher.java:24
6)
    at org.microemu.device.ui.EventDispatcher.post(EventDispatcher.java:164)
    at org.microemu.device.ui.EventDispatcher.run(EventDispatcher.java:99)
    at java.lang.Thread.run(Unknown Source)
Caused by:
org.microemu.app.classloader.MIDletClassLoader$LoadClassByParentException:
javax.microedition.media.PlayerListener
    at
org.microemu.app.classloader.MIDletClassLoader.findClass(MIDletClassLoader.java:
339)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at
org.microemu.app.classloader.MIDletClassLoader.loadClass(MIDletClassLoader.java:
213)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClassInternal(Unknown Source)
    ... 22 more


What version of the product are you using? On what operating system?
Win 7 64 bit,
http://snapshot.microemu.org/microemulator/download/microemulator-3.0.0-SNAPSHOT
.zip
(version from 08-Jan-2010)

Please provide any additional information below.
Works with Microemulator 2.0.3

```

Original issue reported on code.google.com by `sk750gps...@googlemail.com` on 8 Jan 2010 at 9:25

**Comment by GoogleCodeExporter** [comment]
```
Microemulator 3.x starts to implement MIDP 3 standard where all multimedia API 
(javax.microedition.media.*) are moved to the JSR-135. It is needed now to 
include 
microemu-jsr-135.jar for the initial classpath now. 

The plan for 3.0 is to make an UI interface to manage all enabled/disabled 
API's for the 
particular MIDlet, then including microemu-jsr-135.jar won't be necessary. I'll 
keep this 
issue open until JSR's manager is ready.
```

Original comment by `bar...@gmail.com` on 18 Jan 2010 at 8:29
- Changed state: **Accepted**
- Added labels: **Milestone-3.0**
