### ISSUE TITLE
NullPointerException in MicroEmu caused by DB Railnavigator MIDlet

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Perundurai-Products/microemu#29]
```
What steps will reproduce the problem?
1. Configure MicroEmulator as a "resizeable device".
1. Download DB Railnavigator:
   http://railnavigator.bahn.de/bin/pf/query-p2w.exe/dn?p2wMode=h2g
2. Run the MIDlet with MicroEmu 2.0.4, select "Einstellungen", optionally
   select English as the language, select "Fullscreen" Mode / "Vollbild".

What is the expected output? What do you see instead?

DB Railnavigator should switch to fullscreen mode. It does, but after
switching, clicks trigger the wrong main menü entries, ie. not the entry one
thinks he has clicked at. Additionally, the navigation menu at the bottom of
the screen disappears, making navigation impossible.

If you quick Railnavigator now and try to restart it, you'll get following
exception in MicroEmu:

Exception in thread "event-thread" java.lang.NullPointerException
        at a.az.getHeight(Unknown Source)
        at
javax.microedition.lcdui.Displayable.showNotify(Displayable.java:266)
        at javax.microedition.lcdui.Display$1.run(Display.java:523)
        at
org.microemu.device.ui.EventDispatcher$ShowNotifyEvent.run(EventDispatcher.jav
        at
org.microemu.device.ui.EventDispatcher.post(EventDispatcher.java:162)
        at org.microemu.device.ui.EventDispatcher.run(EventDispatcher.java:97)
        at java.lang.Thread.run(Thread.java:619)


What version of the product are you using? On what operating system?

* Java SE 1.6.0_17 x86, Debian GNU/Linux x86
* MicroEmu 2.0.4
* DB Railnavigator R6.60.13, Release 5.24.DB.R6.60.m (H6.60.13)

Please provide any additional information below.

```

Original issue reported on code.google.com by `mails.ad...@gunter.ohrner.net` on 7 Feb 2010 at 10:14

**Comment by GoogleCodeExporter** [comment]
```
I cannot reproduce this error. Can you verify whether it still exists in
MicroEmulator 3.0.0 snapshot version?

Here is the url to the package: 
http://snapshot.microemu.org/microemulator/download/
```

Original comment by `bar...@gmail.com` on 11 Feb 2010 at 3:00

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I just tested it. I removed ~/.microemulator/ and started from scrtach using 
todays
3.0-SNAPSHOT.
I started MicroEmu and the RailNavigator midlet and switched to "resizable 
device".
Railnavigator seems to work much better now in "normal" mode, in that it does 
resize to
full MicroEmu window size.
However, switching Railnavigator to "fullscreen" mode still leads to erratic 
menu
button behaviour, and terminating and restarting Railnavigator in this mode 
still
causes a NullPointerException:

Exception in thread "event-thread" java.lang.NullPointerException
        at a.az.getHeight(Unknown Source)
        at javax.microedition.lcdui.Displayable.showNotify(Displayable.java:257)
        at javax.microedition.lcdui.Display$1.run(Display.java:563)
        at
org.microemu.device.ui.EventDispatcher$RunnableEvent.run(EventDispatcher.java:24
6)
        at org.microemu.device.ui.EventDispatcher.post(EventDispatcher.java:164)
        at org.microemu.device.ui.EventDispatcher.run(EventDispatcher.java:99)
        at java.lang.Thread.run(Thread.java:619)

```

Original comment by `mails.ad...@gunter.ohrner.net` on 12 Feb 2010 at 2:16

**Comment by GoogleCodeExporter** [comment]
```
Mh, additionally, entering capital letters in text fields does not seem to work 
any
more, this worked ok in MicroEmu 2.0.4. Should I open a separate defect report 
for this
issue?
```

Original comment by `mails.ad...@gunter.ohrner.net` on 12 Feb 2010 at 2:26

**Comment by GoogleCodeExporter** [comment]
```
Please open a separate bug report for entering capital letters problem.
```

Original comment by `bar...@gmail.com` on 22 Feb 2010 at 11:29
