### ISSUE TITLE
NullPointerException at org.microemu.android.device.AndroidDeviceDisplay.paintDisplayable(AndroidDeviceDisplay.java:253)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Perundurai-Products/microemu#34]
```
What steps will reproduce the problem?
1. Install
http://www.dashandyticket.de/portals/download/1/1.0/49/dasHandyTicket.jar
2. Buy a ticket - Not very feasible, I know  :-/
3. View ticket, press menu key, "Show Barcode".

What is the expected output?
The barcode shown alone.

What do you see instead?
java.lang.NullPointerException
       at
org.microemu.android.device.AndroidDeviceDisplay.paintDisplayable(AndroidDeviceD
isplay.java:253)
       at
org.microemu.android.device.AndroidDeviceDisplay.repaint(AndroidDeviceDisplay.ja
va:226)
       at
org.microemu.device.ui.EventDispatcher$PaintEvent.run(EventDispatcher.java:185)
       at org.microemu.device.ui.EventDispatcher.post(EventDispatcher.java:164)
       at org.microemu.device.ui.EventDispatcher.run(EventDispatcher.java:95)
       at java.lang.Thread.run(Thread.java:1096)

What version of the product are you using? On what operating system?
microemu-android trunk on Nexus One
```

Original issue reported on code.google.com by `sonic740606` on 17 Mar 2010 at 1:22

**Comment by GoogleCodeExporter** [comment]
```
A simple

DisplayRepaintListener d=displayRepaintListeners.get(i);
if(d!=null) d.repaintInvoked(rectangle);

shows just a black screen.
```

Original comment by `sonic740606` on 17 Mar 2010 at 1:24
