### ISSUE TITLE
DB Railnavigator: java.lang.NoSuchMethodError: a

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Perundurai-Products/microemu#36]
```
What steps will reproduce the problem?
1. Install DB Railnavigator:
http://railnavigator.bahn.de/rnav/dbrailnavigator_std.zip
2. Try to download a train timetable: first menu entry, some start and some
end, "Abrufen" ("Download")

What is the expected output?
The train timetable

What do you see instead?
java.lang.NoSuchMethodError: a
       at a.aw.b(Unknown Source)
       at a.bm.b(Unknown Source)
       at a.u.b(Unknown Source)
       at a.f.<init>(Unknown Source)
       at a.bf.run(Unknown Source)
       at java.lang.Thread.run(Thread.java:1096)

What version of the product are you using?
microemu-android trunk

On what operating system?
Android 2.1
```

Original issue reported on code.google.com by `sonic740606` on 17 Mar 2010 at 7:00

**Comment by GoogleCodeExporter** [comment]
Original comment by `bar...@gmail.com` on 18 Mar 2010 at 10:36
- Changed state: **Accepted**
- Added labels: **Milestone-3.0**

**Comment by GoogleCodeExporter** [comment]
```
Issue 40 has been merged into this issue.
```

Original comment by `bar...@gmail.com` on 26 Mar 2010 at 9:36

**Comment by GoogleCodeExporter** [comment]
```
My findings shows that using ProGuard with overloadaggressively option often 
makes the code which fails with this error.
```

Original comment by `bar...@gmail.com` on 18 Jun 2010 at 6:43

**Comment by GoogleCodeExporter** [comment]
```
Android Dalvik VM has problems when original application is obfuscated with 
some of the settings.

This is a list of the Proguard setting that should be added to the 
configuration:
-dontpreverify
-optimizations !code/simplification/arithmetic

And remove the following:
-overloadaggressively

For more information why Android require these settings read the information at 
the Proguard site:
http://proguard.sourceforge.net/manual/examples.html#androidactivity
```

Original comment by `bar...@gmail.com` on 18 Oct 2011 at 6:44
- Changed state: **WontFix**
- Removed labels: **Milestone-3.0**
