### ISSUE TITLE
JAD file parsing problem MIDlet-X: ....

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Perundurai-Products/microemu#4]
```
Hi,

If you have this in your MIDlet:

MIDlet-1: ContactlessConnectionTestMIDlet,,ds.contactless.javame.tests
.ContactlessConnectionTestMIDlet

(it is wrapped on 72 chars)

this doesn't work if you try to open this JAD file with the emulator
(NullPointerException)


error Message: Error starting MIDlet: Unable to create MIDlet,
java.lang.NullPointerException java.lang.NullPointerException
org.microemu.app.Common.startMidlet(Common.java:417)
java.lang.NullPointerException
at org.microemu.app.Common.startMidlet(Common.java:410)
at org.microemu.app.Common.initMIDlet(Common.java:1039)
at org.microemu.app.Headless.main(Headless.java:120)
at org.microemu.app.Main.main(Main.java:1021)
destroyMIDletContext
org.microemu.app.Common.destroyMIDletContext(Common.java:187)

The problem seems to be located in:
microemu-javase/src/main/java/org/microemu/util/JadProperties.java in the
method "public Vector getMidletEntries()" as it doesn't deal with reading
the Class Name split over multiple lines.
```

Original issue reported on code.google.com by `bar...@gmail.com` on 18 Nov 2009 at 11:06
- Merged into: #66

**Comment by GoogleCodeExporter** [comment]
Original comment by `bar...@gmail.com` on 17 Sep 2010 at 9:57
- Changed state: **Duplicate**
