### ISSUE TITLE
Converted application complies fine, but crashes when run on Android

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Perundurai-Products/microemu#40]
```
Tried to convert the Forumla One Live Timings app to Android using this, got 
it to compile, but the app crashes when executed on the device.

See my post here:

http://androidforums.com/android-applications/52861-formula-1-timings-
app.html#post431723

The original J2ME files are here: 
http://mobile.formula1.com/download/select

Tried using SVN r2339
```

Original issue reported on code.google.com by `mark.gil...@gmail.com` on 25 Mar 2010 at 8:42
- Merged into: #36

**Comment by GoogleCodeExporter** [comment]
```
Included stack trace for that error:

03-25 10:07:18.611: ERROR/AndroidRuntime(254): Uncaught handler: thread main 
exiting
due to uncaught exception
03-25 10:07:18.651: ERROR/AndroidRuntime(254): java.lang.NoSuchMethodError: ab.a
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at ab.a(Unknown Source)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at hl.b(Unknown Source)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at hl.a(Unknown Source)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at fh.a(Unknown Source)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at gw.<init>(Unknown Source)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at gw.a(Unknown Source)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at es.<init>(Unknown Source)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at es.b(Unknown Source)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at gd.<init>(Unknown Source)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at gd.a(Unknown Source)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
com.service2media.m2active.client.j2me.Client.startApp(Unknown Source)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
javax.microedition.midlet.MIDlet$MIDletAccessor.startApp(MIDlet.java:50)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
org.microemu.android.MicroEmulator.onResume(MicroEmulator.java:202)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1149)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
android.app.Activity.performResume(Activity.java:3763)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
android.app.ActivityThread.performResumeActivity(ActivityThread.java:2937)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2965)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
android.app.ActivityThread.access$2200(ActivityThread.java:119)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1863)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
android.os.Handler.dispatchMessage(Handler.java:99)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
android.os.Looper.loop(Looper.java:123)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
android.app.ActivityThread.main(ActivityThread.java:4363)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
java.lang.reflect.Method.invokeNative(Native Method)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
java.lang.reflect.Method.invoke(Method.java:521)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
03-25 10:07:18.651: ERROR/AndroidRuntime(254):     at
dalvik.system.NativeStart.main(Native Method)

```

Original comment by `bar...@gmail.com` on 25 Mar 2010 at 9:10

**Comment by GoogleCodeExporter** [comment]
```
It seems this problem appears in other converted applications.
```

Original comment by `bar...@gmail.com` on 26 Mar 2010 at 9:36
- Changed state: **Duplicate**
